In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', -1)

## Rename multiple CSV files in a folder with Python

In [3]:
import glob, os

def rename(dir, pathAndFilename, pattern, titlePattern):
    os.rename(pathAndFilename, os.path.join(dir, titlePattern))

# search for csv files in the working folder     
path = os.path.expanduser("~/Projects/MYP/Datasets/test/*.csv")

# iterate and rename them one by one with the number of the iteration
for i, fname in enumerate(glob.glob(path)):
    rename(os.path.expanduser('~/Projects/MYP/Datasets/test/'), fname, r'*.csv', r'test{}.csv'.format(i))

## Load several files into Dataframe

In [5]:
# change separator for CSV file
df1 = pd.read_csv('~/Projects/MYP/Datasets/test/test0.csv', sep="@")
df2 = pd.read_csv('~/Projects/MYP/Datasets/test/test1.csv', sep="@")
df3 = pd.read_csv('~/Projects/MYP/Datasets/test/test1.csv', sep="@")

frames = [df1, df2, df3]

# concatenate multiple data CSV files
all = pd.concat(frames)

print(df1.shape)
print(df2.shape)
print(all.shape)

(541, 7)
(550, 7)
(1641, 7)

## Dynamically Load multiple csv file into Dataframe

In [9]:
import glob

result = pd.DataFrame()

path = os.path.expanduser("~/Projects/MYP/Datasets/test/*.csv")

for fname in glob.glob(path):
    head, tail = os.path.split(fname)
    df = pd.read_csv(fname, sep="@")
    df2 = df.sort_values(by=['Views'], ascending=False).drop(['Favorite', 'videoID'], axis=1).iloc[15:20,:]
    df2['channel'] = tail
    result = pd.concat([result, df2])
result.sort_values(by=['channel']).iloc[0:10,]

,title,Views,Like,Dislike,Comment,channel
215,Turning Google Earth into SimCity 2000,168175.0,3251.0,1125.0,215.0,test0.csv
301,Microservices + Events + Docker = A Perfect Trio,161110.0,3213.0,50.0,83.0,test0.csv
265,PHP in 2018 by the Creator of PHP,164577.0,3557.0,69.0,384.0,test0.csv
468,Developing Blockchain Software,169484.0,2512.0,116.0,133.0,test0.csv
398,VS Code: The Last Editor You'll Ever Need,172738.0,1930.0,194.0,340.0,test0.csv
175,Coding Challenge #74: Clock with p5.js,232227.0,4609.0,68.0,289.0,test1.csv
373,Coding Challenge #12: The Lorenz Attractor in Processing,217172.0,3680.0,43.0,333.0,test1.csv
447,10.4: Loading JSON data from a URL (Asynchronous Callbacks!) - p5.js Tutorial,218081.0,2120.0,79.0,240.0,test1.csv
269,The Coding Train!,218635.0,2482.0,83.0,324.0,test1.csv
193,Coding Challenge #71: Minesweeper,220816.0,3334.0,71.0,401.0,test1.csv

## Generate clickable links with pandas and Jupyter notebook

In [11]:
from IPython.display import HTML

# convert url column into href tag and add it as a new column to dataframe
df['nameurl'] = df['videoID'].apply(lambda x: '<a href="{}">XXXXX</a>'.format(x))



# otherwise the link will be blank
pd.set_option('display.max_colwidth', 10)

# in order to display HTML code
HTML(df.iloc[20:30,] .to_html(escape=False))