# Pandas is column is contained in another column in the same row

dataset:

https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset#movie_metadata.csv

In [1]:
# read a dataset movies
import pandas as pd
movies = pd.read_csv('./csv/movie_metadata.csv', usecols=[1,2,3])
movies.head()

       director_name  num_critic_for_reviews  duration
0      James Cameron                   723.0     178.0
1     Gore Verbinski                   302.0     169.0
2         Sam Mendes                   602.0     148.0
3  Christopher Nolan                   813.0     164.0
4        Doug Walker                     NaN       NaN

In [2]:
# read a dataset movies
import pandas as pd
movies = pd.read_csv('./csv/movie_metadata.csv', usecols=['movie_title', 'director_name', 'actor_2_name', 'content_rating','plot_keywords','gross', 'genres'])
movies.tail()

,director_name,actor_2_name,gross,genres,movie_title,plot_keywords,content_rating
5038,Scott Smith,Daphne Zuniga,NaN,Comedy|Drama,Signed Sealed Delivered,fraud|postal worker|prison|theft|trial,NaN
5039,NaN,Valorie Curry,NaN,Crime|Drama|Mystery|Thriller,The Following,cult|fbi|hideout|prison escape|serial killer,TV-14
5040,Benjamin Roberds,Maxwell Moody,NaN,Drama|Horror|Thriller,A Plague So Pleasant,NaN,NaN
5041,Daniel Hsia,Daniel Henney,10443.0,Comedy|Drama|Romance,Shanghai Calling,NaN,PG-13
5042,Jon Gunn,Brian Herzlinger,85222.0,Documentary,My Date with Drew,actress name in title|crush|date|four word tit...,PG

## Compare if two columns match

In [3]:
# check if two columns in a single row are identical
df2 = movies.loc[(movies.director_name == movies.actor_2_name), ['movie_title', 'director_name', 'actor_2_name']]
df2.head()

                   movie_title       director_name        actor_2_name
437           The Expendables   Sylvester Stallone  Sylvester Stallone
504                    Oceans       Jacques Perrin      Jacques Perrin
600   Star Trek: Insurrection      Jonathan Frakes     Jonathan Frakes
931                       Ted      Seth MacFarlane     Seth MacFarlane
1057               Dick Tracy        Warren Beatty       Warren Beatty

## Filter on two conditions

In [4]:
# several condtitions can be applied with loc
df2 = movies.loc[(movies.gross > 100000000.0) & (movies.genres == 'Action|Adventure|Fantasy'), :]
df2.head()

,director_name,actor_2_name,gross,genres,movie_title,plot_keywords,content_rating
1,Gore Verbinski,Orlando Bloom,309404152.0,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,goddess|marriage ceremony|marriage proposal|pi...,PG-13
13,Gore Verbinski,Orlando Bloom,423032628.0,Action|Adventure|Fantasy,Pirates of the Caribbean: Dead Man's Chest,box office hit|giant squid|heart|liar's dice|m...,PG-13
18,Rob Marshall,Sam Claflin,241063875.0,Action|Adventure|Fantasy,Pirates of the Caribbean: On Stranger Tides,blackbeard|captain|pirate|revenge|soldier,PG-13
21,Marc Webb,Andrew Garfield,262030663.0,Action|Adventure|Fantasy,The Amazing Spider-Man,lizard|outcast|spider|spider man|teenager,PG-13
54,Steven Spielberg,Ray Winstone,317011114.0,Action|Adventure|Fantasy,Indiana Jones and the Kingdom of the Crystal S...,cult figure|femme fatale|indiana jones|unsubti...,PG-13

## Search if a column is part of another column on the same row

In [5]:
movies['rat'] = movies.content_rating.astype(str)

In [6]:
movies.head()

,director_name,actor_2_name,gross,genres,movie_title,plot_keywords,content_rating,rat
0,James Cameron,Joel David Moore,760505847.0,Action|Adventure|Fantasy|Sci-Fi,Avatar,avatar|future|marine|native|paraplegic,PG-13,PG-13
1,Gore Verbinski,Orlando Bloom,309404152.0,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,goddess|marriage ceremony|marriage proposal|pi...,PG-13,PG-13
2,Sam Mendes,Rory Kinnear,200074175.0,Action|Adventure|Thriller,Spectre,bomb|espionage|sequel|spy|terrorist,PG-13,PG-13
3,Christopher Nolan,Christian Bale,448130642.0,Action|Thriller,The Dark Knight Rises,deception|imprisonment|lawlessness|police offi...,PG-13,PG-13
4,Doug Walker,Rob Walker,NaN,Documentary,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,nan

## Using lambda expression

* **Axis 0** iterate on all the ROWS in each COLUMN
* **Axis 1** iterate on all the COLUMNS in each ROW

In [11]:
df_filter = movies[movies.apply(lambda row: row.rat in row.movie_title, axis=1)]
df_filter[['content_rating','movie_title']].head()

    content_rating                          movie_title
94               R  Terminator 3: Rise of the Machines
124              R              The Matrix Revolutions
126              R                 The Matrix Reloaded
128              R                  Mad Max: Fury Road
179              R                        The Revenant

In [16]:
df_filter = movies[movies.apply(lambda row: row.movie_title.find(row.rat) != -1, axis=1)]
df_filter[['content_rating','movie_title']].head()

    content_rating                          movie_title
94               R  Terminator 3: Rise of the Machines
124              R              The Matrix Revolutions
126              R                 The Matrix Reloaded
128              R                  Mad Max: Fury Road
179              R                        The Revenant

In [13]:
'Terminator 3: Rise of the Machines'.find('R')

14

In [14]:
'Terminator 3: Rise of the Machines'.find('A')

-1

In [ ]:
'Terminator 3: Rise of the Machines'.find('A') != -1

## Using for loop and series to search

In [17]:
rating_list = movies['content_rating']
title_list = movies['movie_title']

In [20]:
is_part = []
for i, rate in enumerate(rating_list):
    if not pd.isna(title_list[i]) and (str(rate) in title_list[i]):
        is_part.append(True)
    else:
        is_part.append(False)
is_part[:5]

[False, False, False, False, False]

In [19]:
movies[is_part][['content_rating','movie_title']].head()

    content_rating                          movie_title
94               R  Terminator 3: Rise of the Machines
124              R              The Matrix Revolutions
126              R                 The Matrix Reloaded
128              R                  Mad Max: Fury Road
179              R                        The Revenant

## search part of a column it it contained in another column?

In [21]:
keywords_list = movies['plot_keywords']
title_list = movies['movie_title']
keys_list = movies['plot_keywords'].str.split('|').str.get(0)
keys_list[:5]

0       avatar
1      goddess
2         bomb
3    deception
4          NaN
Name: plot_keywords, dtype: object

In [22]:
title_list[:5]

0                                              Avatar
1            Pirates of the Caribbean: At World's End
2                                             Spectre
3                               The Dark Knight Rises
4    Star Wars: Episode VII - The Force Awakens    ...
Name: movie_title, dtype: object

In [23]:
is_part = []
for i, key in enumerate(keys_list):
    if not pd.isna(title_list[i]) and (str(key) in title_list[i]):
        is_part.append(True)
    else:
        is_part.append(False)
is_part[:5]

[False, False, False, False, False]

In [24]:
movies[is_part][['plot_keywords','movie_title']]

,plot_keywords,movie_title
620,ball|blood|skating|song|year 2005,Rollerball
989,boy|bully|dream|dream sequence|planet,The Adventures of Sharkboy and Lavagirl 3-D
1767,cop|corrupt politician|future|senator|time travel,Timecop
4185,ape|fear|future|spacecraft|spaceship,Escape from the Planet of the Apes

In [29]:
is_part = []
for i, key in enumerate(keys_list):
    if not pd.isna(title_list[i]) and (str(key) in title_list[i] or str(key).lower() == title_list[i].strip().lower()):
        is_part.append(True)
    else:
        is_part.append(False)
is_part

[True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

In [31]:
movies[is_part][['plot_keywords','movie_title']]

,plot_keywords,movie_title
0,avatar|future|marine|native|paraplegic,Avatar
33,alice in wonderland|mistaking reality for drea...,Alice in Wonderland
196,australia|cattle|darwin|drover|japanese,Australia
620,ball|blood|skating|song|year 2005,Rollerball
742,contagion|cure|infection|panic|virus,Contagion
833,anger management|argument|irony|sarcasm|therapist,Anger Management
847,casper|friendly ghost|ghost|maine|mansion,Casper
888,burlesque|dancer|iowa|small town girl|stage,Burlesque
890,lolita|nymphet|older man young girl relationsh...,Lolita
989,boy|bully|dream|dream sequence|planet,The Adventures of Sharkboy and Lavagirl 3-D
1160,cleopatra|egypt|epic|queen|roman empire,Cleopatra
1580,arachnophobia|death|doctor|small town|spider,Arachnophobia
1767,cop|corrupt politician|future|senator|time travel,Timecop
1997,blindness|epidemic|hospital|pubic hair|quarantine,Blindness
2175,drumline|drummer|fish out of water|marching ba...,Drumline
2186,boogeyman|childhood|fear|hometown|uncle,Boogeyman
2318,flash of genius|genius|intellectual property|p...,Flash of Genius
2349,ramanujan,Ramanujan
2481,hitman|impersonation|see through dress|topless...,Hitman
2492,halloween|masked killer|michael myers|slasher|...,Halloween
2619,halloween|masked killer|michael myers|slasher|...,Halloween
2911,machete|mexican|mexico|priest|texas,Machete
2981,celebrity|journalist|lesbian kiss|strong femal...,Celebrity
3036,phone booth|publicist|single set production|sn...,Phone Booth
3113,devil|elevator|hit and run|throat slitting|tra...,Devil
3277,alien|creature|future|outer space|spaceship,Alien
3617,college|face slap|high school|loss of virginit...,College
3745,april fool's day|island|mansion|psycho|secret,April Fool's Day
4109,freeway|nightmare|police|school|trailer park,Freeway
4128,alice in wonderland|mistaking reality for drea...,Alice in Wonderland
4185,ape|fear|future|spacecraft|spaceship,Escape from the Planet of the Apes
4256,lolita|nymphet|older man young girl relationsh...,Lolita
4393,caramel|friendship|police|secret|suitor,Caramel
4821,halloween|masked killer|michael myers|slasher|...,Halloween
4939,aroused|photography|pornography documentary|po...,Aroused

## Performance tests

* for loop and comparison - 8.304 seconds
* lambda expresion - 25.893 seconds

In [32]:
import cProfile
import pandas as pd
movies = pd.read_csv('./csv/movie_metadata.csv')
movies['rat'] = movies.content_rating.astype(str)


def before(movies):
    for i in range(1, 100):
        is_part = []
        title_list = movies['movie_title']
        genre_list = movies['content_rating']
        for i, genre in enumerate(genre_list):
            if str(genre) in title_list[i]:
                is_part.append(True)
            else:
                is_part.append(False)
        movies[is_part]


def after(movies):
    for i in range(1, 100):
        movies[movies.apply(lambda x: x.rat in x.movie_title, axis=1)]


cProfile.run("before(movies)")
cProfile.run("after(movies)")

         18545451 function calls (18544652 primitive calls) in 8.718 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      198    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:416(parent)
     1290    0.001    0.000    0.002    0.000 <frozen importlib._bootstrap>:997(_handle_fromlist)
        1    0.498    0.498    8.718    8.718 <ipython-input-32-65c665059bae>:7(before)
        1    0.000    0.000    8.718    8.718 <string>:1(<module>)
      100    0.000    0.000    0.000    0.000 __init__.py:205(iteritems)
      497    0.000    0.000    0.003    0.000 _methods.py:42(_any)
      297    0.000    0.000    0.001    0.000 algorithms.py:1421(_get_take_nd_function)
      297    0.003    0.000    0.031    0.000 algorithms.py:1548(take_nd)
        1    0.000    0.000    0.000    0.000 base.py:1569(is_unique)
   499257    0.441    0.000    1.580    0.000 base.py:1647(_convert_scalar_indexer)
        2    0.000    0.000    0.000    0.000 base.py:1935(_engine)
        2    0.000    0.000    0.000    0.000 base.py:1938(<lambda>)
      297    0.001    0.000    0.001    0.000 base.py:2033(__contains__)
        4    0.000    0.000    0.000    0.000 base.py:2067(__getitem__)
       99    0.000    0.000    0.010    0.000 base.py:2179(take)
       99    0.000    0.000    0.002    0.000 base.py:2445(equals)
       99    0.002    0.000    0.007    0.000 base.py:255(__new__)
        8    0.000    0.000    0.000    0.000 base.py:3071(get_loc)
   499257    1.162    0.000    7.143    0.000 base.py:3090(get_value)
   499257    0.120    0.000    0.183    0.000 base.py:4117(_maybe_cast_indexer)
      100    0.000    0.000    0.001    0.000 base.py:473(_simple_new)
      204    0.000    0.000    0.000    0.000 base.py:4914(_ensure_index)
       99    0.001    0.000    0.008    0.000 base.py:520(_shallow_copy_with_infer)
     1685    0.001    0.000    0.003    0.000 base.py:61(is_dtype)
       99    0.000    0.000    0.000    0.000 base.py:615(is_)
      100    0.000    0.000    0.000    0.000 base.py:635(_reset_identity)
      799    0.000    0.000    0.000    0.000 base.py:641(__len__)
       99    0.000    0.000    0.000    0.000 base.py:662(dtype)
      301    0.000    0.000    0.000    0.000 base.py:672(values)
        2    0.000    0.000    0.000    0.000 base.py:677(_values)
      198    0.000    0.000    0.000    0.000 base.py:711(get_values)
        2    0.000    0.000    0.000    0.000 base.py:789(_ndarray_values)
       99    0.000    0.000    0.005    0.000 base.py:893(tolist)
       99    0.000    0.000    0.000    0.000 base.py:904(_coerce_to_ndarray)
       99    0.000    0.000    0.005    0.000 base.py:912(__iter__)
       99    0.000    0.000    0.000    0.000 base.py:920(_get_attributes_dict)
       99    0.000    0.000    0.000    0.000 base.py:922(<dictcomp>)
      297    0.001    0.000    0.008    0.000 cast.py:257(maybe_promote)
       99    0.001    0.000    0.011    0.000 common.py:100(is_bool_indexer)
       99    0.000    0.000    0.001    0.000 common.py:1043(is_datetime64_any_dtype)
      401    0.000    0.000    0.001    0.000 common.py:122(is_sparse)
      993    0.002    0.000    0.006    0.000 common.py:1688(is_extension_array_dtype)
      792    0.000    0.000    0.001    0.000 common.py:1784(_get_dtype)
      594    0.001    0.000    0.002    0.000 common.py:1835(_get_dtype_type)
        1    0.000    0.000    0.000    0.000 common.py:195(is_categorical)
      991    0.000    0.000    0.004    0.000 common.py:227(is_datetimetz)
      198    0.000    0.000    0.001    0.000 common.py:332(is_datetime64_dtype)
     1189    0.001    0.000    0.003    0.000 common.py:369(is_datetime64tz_dtype)
   499554    0.125    0.000    0.169    0.000 common.py:395(_apply_if_callable)
      198    0.000    0.000    0.001    0.000 common.py:407(is_timedelta64_dtype)
      495    0.000    0.000    0.001    0.000 common.py:477(is_interval_dtype)
      199    0.000    0.000    0.000    0.000 common.py:513(is_categorical_dtype)
       99    0.000    0.000    0.001    0.000 common.py:647(is_datetimelike)
      396    0.000    0.000    0.001    0.000 common.py:692(is_dtype_equal)
       99    0.000    0.000    0.000    0.000 common.py:858(is_signed_integer_dtype)
       99    0.000    0.000    0.001    0.000 common.py:89(is_object_dtype)
        4    0.000    0.000    0.000    0.000 concat.py:105(_get_sliced_frame_result_type)
       99    0.000    0.000    0.001    0.000 dtypes.py:401(__new__)
       99    0.000    0.000    0.001    0.000 dtypes.py:459(construct_from_string)
      396    0.001    0.000    0.001    0.000 dtypes.py:707(is_dtype)
      297    0.002    0.000    0.098    0.000 frame.py:2664(__getitem__)
      198    0.000    0.000    0.001    0.000 frame.py:2690(_getitem_column)
       99    0.001    0.000    0.094    0.001 frame.py:2707(_getitem_array)
        4    0.000    0.000    0.000    0.000 frame.py:3093(_box_item_values)
        4    0.000    0.000    0.000    0.000 frame.py:3100(_box_col_values)
       99    0.000    0.000    0.000    0.000 frame.py:320(_constructor)
       99    0.000    0.000    0.001    0.000 frame.py:334(__init__)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:49(_wrapfunc)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:882(argsort)
      103    0.000    0.000    0.000    0.000 generic.py:124(__init__)
       99    0.000    0.000    0.000    0.000 generic.py:178(_init_mgr)
      198    0.000    0.000    0.000    0.000 generic.py:2484(_get_item_cache)
        4    0.000    0.000    0.000    0.000 generic.py:2498(_set_as_cached)
        1    0.000    0.000    0.000    0.000 generic.py:2577(_clear_item_cache)
       99    0.000    0.000    0.000    0.000 generic.py:2603(_set_is_copy)
       99    0.001    0.000    0.071    0.001 generic.py:2783(_take)
       99    0.000    0.000    0.000    0.000 generic.py:364(_get_axis_number)
      198    0.000    0.000    0.000    0.000 generic.py:377(_get_axis_name)
      198    0.000    0.000    0.001    0.000 generic.py:390(_get_axis)
       99    0.000    0.000    0.000    0.000 generic.py:394(_get_block_manager_axis)
       99    0.000    0.000    0.000    0.000 generic.py:4345(__finalize__)
        4    0.000    0.000    0.000    0.000 generic.py:4362(__getattr__)
      210    0.000    0.000    0.000    0.000 generic.py:4378(__setattr__)
       99    0.000    0.000    0.002    0.000 generic.py:4423(_protect_consolidate)
       99    0.000    0.000    0.002    0.000 generic.py:4433(_consolidate_inplace)
       99    0.000    0.000    0.002    0.000 generic.py:4436(f)
   504025    0.178    0.000    0.254    0.000 generic.py:7(_check)
       99    0.000    0.000    0.000    0.000 indexing.py:2321(convert_to_index_sliceable)
       99    0.000    0.000    0.010    0.000 indexing.py:2345(check_bool_indexer)
       99    0.002    0.000    0.004    0.000 indexing.py:2441(maybe_convert_indices)
        4    0.000    0.000    0.000    0.000 inference.py:415(is_hashable)
      302    0.001    0.000    0.001    0.000 internals.py:116(__init__)
      297    0.001    0.000    0.036    0.000 internals.py:1237(take_nd)
      302    0.000    0.000    0.000    0.000 internals.py:127(_check_ndim)
        8    0.000    0.000    0.000    0.000 internals.py:166(_consolidate_key)
   499554    0.069    0.000    0.069    0.000 internals.py:203(internal_values)
   499257    0.142    0.000    0.290    0.000 internals.py:222(to_dense)
      297    0.000    0.000    0.000    0.000 internals.py:229(fill_value)
      104    0.000    0.000    0.001    0.000 internals.py:2298(__init__)
     1206    0.000    0.000    0.000    0.000 internals.py:233(mgr_locs)
      302    0.000    0.000    0.000    0.000 internals.py:237(mgr_locs)
      301    0.000    0.000    0.003    0.000 internals.py:269(make_block_same_class)
        1    0.000    0.000    0.000    0.000 internals.py:3148(get_block_type)
      302    0.001    0.000    0.002    0.000 internals.py:3191(make_block)
      100    0.000    0.000    0.008    0.000 internals.py:3265(__init__)
      100    0.000    0.000    0.000    0.000 internals.py:3266(<listcomp>)
      401    0.001    0.000    0.002    0.000 internals.py:3307(shape)
     1203    0.000    0.000    0.001    0.000 internals.py:3309(<genexpr>)
      400    0.000    0.000    0.000    0.000 internals.py:3311(ndim)
      101    0.002    0.000    0.004    0.000 internals.py:3363(_rebuild_blknos_and_blklocs)
      108    0.000    0.000    0.000    0.000 internals.py:3384(_get_items)
      301    0.000    0.000    0.000    0.000 internals.py:348(shape)
      100    0.001    0.000    0.002    0.000 internals.py:3488(_verify_integrity)
      401    0.000    0.000    0.000    0.000 internals.py:3490(<genexpr>)
   499867    0.101    0.000    0.101    0.000 internals.py:352(dtype)
      305    0.000    0.000    0.001    0.000 internals.py:356(ftype)
        4    0.000    0.000    0.000    0.000 internals.py:372(iget)
      298    0.000    0.000    0.000    0.000 internals.py:3776(is_consolidated)
      101    0.000    0.000    0.001    0.000 internals.py:3784(_consolidate_check)
      101    0.000    0.000    0.001    0.000 internals.py:3785(<listcomp>)
       99    0.000    0.000    0.001    0.000 internals.py:4085(consolidate)
      199    0.000    0.000    0.001    0.000 internals.py:4101(_consolidate_inplace)
        4    0.000    0.000    0.000    0.000 internals.py:4108(get)
        4    0.000    0.000    0.000    0.000 internals.py:4137(iget)
       99    0.000    0.000    0.046    0.000 internals.py:4388(reindex_indexer)
       99    0.000    0.000    0.037    0.000 internals.py:4423(<listcomp>)
       99    0.001    0.000    0.063    0.001 internals.py:4518(take)
        4    0.000    0.000    0.000    0.000 internals.py:4639(__init__)
  1498068    0.278    0.000    0.278    0.000 internals.py:4684(_block)
   499257    0.254    0.000    0.453    0.000 internals.py:4718(dtype)
   499554    0.266    0.000    0.429    0.000 internals.py:4745(internal_values)
   499257    0.357    0.000    0.856    0.000 internals.py:4752(get_values)
        1    0.000    0.000    0.001    0.001 internals.py:5057(_consolidate)
        8    0.000    0.000    0.000    0.000 internals.py:5063(<lambda>)
        3    0.000    0.000    0.001    0.000 internals.py:5074(_merge_blocks)
        1    0.000    0.000    0.000    0.000 internals.py:5088(<listcomp>)
        1    0.000    0.000    0.000    0.000 internals.py:5089(<listcomp>)
        3    0.000    0.000    0.000    0.000 internals.py:5101(_extend_blocks)
        1    0.000    0.000    0.000    0.000 internals.py:5127(_vstack)
        4    0.000    0.000    0.000    0.000 missing.py:112(_isna_new)
        4    0.000    0.000    0.000    0.000 missing.py:32(isna)
       99    0.000    0.000    0.000    0.000 missing.py:376(array_equivalent)
        4    0.000    0.000    0.000    0.000 numeric.py:110(is_all_dates)
   499257    0.530    0.000    2.293    0.000 numeric.py:179(_convert_scalar_indexer)
      100    0.000    0.000    0.002    0.000 numeric.py:35(__new__)
      693    0.000    0.000    0.020    0.000 numeric.py:433(asarray)
      101    0.000    0.000    0.001    0.000 numeric.py:504(asanyarray)
        1    0.000    0.000    0.000    0.000 numeric.py:630(require)
       99    0.000    0.000    0.008    0.000 numeric.py:64(_shallow_copy)
        2    0.000    0.000    0.000    0.000 numeric.py:701(<genexpr>)
        1    0.000    0.000    0.000    0.000 range.py:169(_data)
        1    0.000    0.000    0.000    0.000 range.py:173(_int64index)
       99    0.000    0.000    0.009    0.000 range.py:260(_shallow_copy)
   499461    0.280    0.000    0.406    0.000 range.py:481(__len__)
        4    0.000    0.000    0.000    0.000 series.py:166(__init__)
        4    0.000    0.000    0.000    0.000 series.py:365(_set_axis)
        4    0.000    0.000    0.000    0.000 series.py:391(_set_subtyp)
        4    0.000    0.000    0.000    0.000 series.py:401(name)
        4    0.000    0.000    0.000    0.000 series.py:405(name)
   499257    0.218    0.000    0.671    0.000 series.py:412(dtype)
   499554    0.181    0.000    0.610    0.000 series.py:465(_values)
   499257    0.175    0.000    1.031    0.000 series.py:476(get_values)
   499257    0.703    0.000    8.076    0.000 series.py:764(__getitem__)
        1    0.000    0.000    0.000    0.000 shape_base.py:182(vstack)
        1    0.000    0.000    0.000    0.000 shape_base.py:234(<listcomp>)
        2    0.000    0.000    0.000    0.000 shape_base.py:63(atleast_2d)
      100    0.000    0.000    0.000    0.000 {built-in method __new__ of type object at 0x9cff80}
   499554    0.044    0.000    0.044    0.000 {built-in method builtins.callable}
        1    0.000    0.000    8.718    8.718 {built-in method builtins.exec}
  1504621    0.482    0.000    1.091    0.000 {built-in method builtins.getattr}
     2581    0.001    0.000    0.001    0.000 {built-in method builtins.hasattr}
      301    0.000    0.000    0.000    0.000 {built-in method builtins.hash}
  1013118    0.337    0.000    0.590    0.000 {built-in method builtins.isinstance}
     2089    0.000    0.000    0.000    0.000 {built-in method builtins.issubclass}
      199    0.000    0.000    0.000    0.000 {built-in method builtins.iter}
503778/502979    0.200    0.000    0.606    0.000 {built-in method builtins.len}
   499461    0.126    0.000    0.126    0.000 {built-in method builtins.max}
        1    0.000    0.000    0.000    0.000 {built-in method builtins.sorted}
      100    0.000    0.000    0.000    0.000 {built-in method builtins.sum}
      305    0.001    0.000    0.001    0.000 {built-in method numpy.core.multiarray.arange}
   500052    0.145    0.000    0.145    0.000 {built-in method numpy.core.multiarray.array}
        2    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.concatenate}
      499    0.001    0.000    0.001    0.000 {built-in method numpy.core.multiarray.empty}
      297    0.000    0.000    0.000    0.000 {built-in method pandas._libs.algos.ensure_int64}
       99    0.000    0.000    0.000    0.000 {built-in method pandas._libs.algos.ensure_platform_int}
   998811    0.122    0.000    0.122    0.000 {built-in method pandas._libs.lib.is_float}
       99    0.000    0.000    0.000    0.000 {built-in method pandas._libs.lib.is_integer}
   499265    0.061    0.000    0.061    0.000 {built-in method pandas._libs.lib.is_scalar}
        4    0.000    0.000    0.000    0.000 {built-in method pandas._libs.missing.checknull}
      497    0.000    0.000    0.003    0.000 {method 'any' of 'numpy.ndarray' objects}
   499262    0.041    0.000    0.041    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'argsort' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {method 'clear' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
      202    0.000    0.000    0.000    0.000 {method 'fill' of 'numpy.ndarray' objects}
      305    0.001    0.000    0.001    0.000 {method 'format' of 'str' objects}
      792    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
        8    0.000    0.000    0.000    0.000 {method 'get_loc' of 'pandas._libs.index.IndexEngine' objects}
   499257    0.452    0.000    0.452    0.000 {method 'get_value' of 'pandas._libs.index.IndexEngine' objects}
      199    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
       99    0.001    0.000    0.001    0.000 {method 'nonzero' of 'numpy.ndarray' objects}
      497    0.003    0.000    0.003    0.000 {method 'reduce' of 'numpy.ufunc' objects}
      198    0.000    0.000    0.000    0.000 {method 'rpartition' of 'str' objects}
       99    0.000    0.000    0.000    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
       99    0.000    0.000    0.000    0.000 {method 'setdefault' of 'dict' objects}
       99    0.000    0.000    0.000    0.000 {method 'take' of 'numpy.ndarray' objects}
       99    0.002    0.000    0.002    0.000 {method 'tolist' of 'numpy.ndarray' objects}
       99    0.000    0.000    0.000    0.000 {method 'update' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {method 'upper' of 'str' objects}
   499558    0.148    0.000    0.148    0.000 {method 'view' of 'numpy.ndarray' objects}
       99    0.003    0.000    0.003    0.000 {pandas._libs.algos.take_2d_axis1_float64_float64}
       99    0.001    0.000    0.001    0.000 {pandas._libs.algos.take_2d_axis1_int64_int64}
       99    0.008    0.000    0.008    0.000 {pandas._libs.algos.take_2d_axis1_object_object}
   998712    0.411    0.000    1.443    0.000 {pandas._libs.lib.values_from_object}

         53174395 function calls (51174298 primitive calls) in 26.802 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      198    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:416(parent)
     2574    0.002    0.000    0.004    0.000 <frozen importlib._bootstrap>:997(_handle_fromlist)
        1    0.065    0.065   26.802   26.802 <ipython-input-32-65c665059bae>:20(after)
   499257    0.860    0.000   21.422    0.000 <ipython-input-32-65c665059bae>:22(<lambda>)
        1    0.000    0.000   26.802   26.802 <string>:1(<module>)
       99    0.000    0.000    0.000    0.000 __init__.py:205(iteritems)
       99    0.000    0.000    0.009    0.000 _decorators.py:136(wrapper)
      594    0.000    0.000    0.004    0.000 _methods.py:42(_any)
       99    0.000    0.000    0.001    0.000 _methods.py:45(_all)
      990    0.001    0.000    0.001    0.000 _weakrefset.py:70(__contains__)
      891    0.002    0.000    0.003    0.000 abc.py:180(__instancecheck__)
      396    0.001    0.000    0.001    0.000 algorithms.py:1421(_get_take_nd_function)
      396    0.004    0.000    0.033    0.000 algorithms.py:1548(take_nd)
       99    0.000    0.000    0.000    0.000 apply.py:101(agg_axis)
       99    0.001    0.000   26.656    0.269 apply.py:105(get_result)
       99    0.000    0.000    0.001    0.000 apply.py:14(frame_apply)
       99    0.003    0.000   26.655    0.269 apply.py:219(apply_standard)
       99    0.000    0.000    0.000    0.000 apply.py:34(__init__)
       99    0.000    0.000    0.000    0.000 apply.py:85(columns)
       99    0.000    0.000    0.192    0.002 apply.py:93(values)
       99    0.000    0.000    0.019    0.000 apply.py:97(dtypes)
       99    0.000    0.000    0.000    0.000 base.py:1442(_has_complex_internals)
   998514    0.450    0.000    1.705    0.000 base.py:1590(is_object)
   998514    0.935    0.000    2.817    0.000 base.py:1647(_convert_scalar_indexer)
        1    0.000    0.000    0.000    0.000 base.py:1976(is_all_dates)
   998613    0.649    0.000    0.784    0.000 base.py:2033(__contains__)
   998514    0.670    0.000    3.158    0.000 base.py:2101(_can_hold_identifiers_and_holds_name)
       99    0.000    0.000    0.010    0.000 base.py:2179(take)
       99    0.000    0.000    0.002    0.000 base.py:2445(equals)
       99    0.002    0.000    0.007    0.000 base.py:255(__new__)
   998514    2.477    0.000   13.285    0.000 base.py:3090(get_value)
       99    0.000    0.000    0.001    0.000 base.py:473(_simple_new)
   999306    0.296    0.000    0.421    0.000 base.py:4914(_ensure_index)
       99    0.000    0.000    0.008    0.000 base.py:520(_shallow_copy_with_infer)
     9702    0.005    0.000    0.011    0.000 base.py:61(is_dtype)
       99    0.000    0.000    0.000    0.000 base.py:615(is_)
       99    0.000    0.000    0.000    0.000 base.py:635(_reset_identity)
  1999602    0.545    0.000    0.763    0.000 base.py:641(__len__)
      100    0.000    0.000    0.000    0.000 base.py:662(dtype)
      496    0.000    0.000    0.001    0.000 base.py:672(values)
      198    0.000    0.000    0.000    0.000 base.py:711(get_values)
       99    0.000    0.000    0.000    0.000 base.py:904(_coerce_to_ndarray)
       99    0.000    0.000    0.000    0.000 base.py:920(_get_attributes_dict)
       99    0.000    0.000    0.000    0.000 base.py:922(<dictcomp>)
       99    0.001    0.000    0.006    0.000 cast.py:1093(find_common_type)
      198    0.000    0.000    0.000    0.000 cast.py:1118(<genexpr>)
      396    0.000    0.000    0.000    0.000 cast.py:1121(<genexpr>)
      198    0.000    0.000    0.000    0.000 cast.py:1126(<genexpr>)
      198    0.000    0.000    0.000    0.000 cast.py:1128(<genexpr>)
      396    0.000    0.000    0.001    0.000 cast.py:1133(<genexpr>)
      297    0.000    0.000    0.001    0.000 cast.py:1232(construct_1d_ndarray_preserving_na)
      297    0.001    0.000    0.008    0.000 cast.py:257(maybe_promote)
      495    0.001    0.000    0.001    0.000 cast.py:853(maybe_castable)
       99    0.001    0.000    0.002    0.000 cast.py:867(maybe_infer_to_datetimelike)
      297    0.002    0.000    0.008    0.000 cast.py:971(maybe_cast_to_datetime)
       99    0.000    0.000    0.001    0.000 common.py:100(is_bool_indexer)
       99    0.000    0.000    0.001    0.000 common.py:1043(is_datetime64_any_dtype)
      198    0.000    0.000    0.001    0.000 common.py:1170(is_datetime_or_timedelta_dtype)
     4257    0.001    0.000    0.010    0.000 common.py:122(is_sparse)
       99    0.000    0.000    0.001    0.000 common.py:1405(needs_i8_conversion)
      198    0.000    0.000    0.000    0.000 common.py:1527(is_float_dtype)
      396    0.000    0.000    0.001    0.000 common.py:1578(is_bool_dtype)
     3267    0.003    0.000    0.028    0.000 common.py:1629(is_extension_type)
     1386    0.002    0.000    0.008    0.000 common.py:1688(is_extension_array_dtype)
     1089    0.001    0.000    0.001    0.000 common.py:1784(_get_dtype)
  1001286    0.431    0.000    0.562    0.000 common.py:1835(_get_dtype_type)
     3564    0.002    0.000    0.011    0.000 common.py:195(is_categorical)
      396    0.002    0.000    0.002    0.000 common.py:1965(pandas_dtype)
     4752    0.002    0.000    0.015    0.000 common.py:227(is_datetimetz)
      594    0.001    0.000    0.002    0.000 common.py:332(is_datetime64_dtype)
     5148    0.002    0.000    0.008    0.000 common.py:369(is_datetime64tz_dtype)
   998613    0.237    0.000    0.333    0.000 common.py:395(_apply_if_callable)
      396    0.000    0.000    0.001    0.000 common.py:407(is_timedelta64_dtype)
       99    0.000    0.000    0.000    0.000 common.py:444(is_period_dtype)
      693    0.000    0.000    0.002    0.000 common.py:477(is_interval_dtype)
     3960    0.002    0.000    0.006    0.000 common.py:513(is_categorical_dtype)
       99    0.000    0.000    0.000    0.000 common.py:546(is_string_dtype)
      495    0.000    0.000    0.001    0.000 common.py:692(is_dtype_equal)
       99    0.000    0.000    0.000    0.000 common.py:811(is_integer_dtype)
       99    0.000    0.000    0.000    0.000 common.py:858(is_signed_integer_dtype)
   999306    0.563    0.000    1.258    0.000 common.py:89(is_object_dtype)
       99    0.000    0.000    0.000    0.000 common.py:995(is_int_or_datetime_dtype)
      198    0.000    0.000    0.000    0.000 dtypes.py:266(construct_from_string)
       99    0.000    0.000    0.001    0.000 dtypes.py:401(__new__)
       99    0.000    0.000    0.001    0.000 dtypes.py:459(construct_from_string)
       99    0.000    0.000    0.000    0.000 dtypes.py:584(is_dtype)
      594    0.001    0.000    0.002    0.000 dtypes.py:707(is_dtype)
       99    0.001    0.000    0.079    0.001 frame.py:2664(__getitem__)
       99    0.001    0.000    0.077    0.001 frame.py:2707(_getitem_array)
       99    0.000    0.000    0.000    0.000 frame.py:320(_constructor)
       99    0.000    0.000    0.001    0.000 frame.py:334(__init__)
       99    0.000    0.000    0.000    0.000 frame.py:555(shape)
       99    0.001    0.000   26.658    0.269 frame.py:5837(apply)
       99    0.000    0.000    0.000    0.000 frame.py:7047(_get_agg_axis)
       99    0.000    0.000    0.000    0.000 function.py:38(__call__)
      693    0.001    0.000    0.001    0.000 generic.py:124(__init__)
       99    0.000    0.000    0.001    0.000 generic.py:1490(__hash__)
      198    0.000    0.000    0.002    0.000 generic.py:164(_validate_dtype)
       99    0.000    0.000    0.000    0.000 generic.py:178(_init_mgr)
       99    0.000    0.000    0.000    0.000 generic.py:2603(_set_is_copy)
       99    0.001    0.000    0.068    0.001 generic.py:2783(_take)
      297    0.001    0.000    0.001    0.000 generic.py:364(_get_axis_number)
      297    0.001    0.000    0.001    0.000 generic.py:377(_get_axis_name)
      297    0.000    0.000    0.001    0.000 generic.py:390(_get_axis)
       99    0.000    0.000    0.001    0.000 generic.py:394(_get_block_manager_axis)
      297    0.000    0.000    0.001    0.000 generic.py:4345(__finalize__)
   999306    1.556    0.000   20.563    0.000 generic.py:4362(__getattr__)
      891    0.003    0.000    0.005    0.000 generic.py:4378(__setattr__)
   998613    0.367    0.000    0.633    0.000 generic.py:438(_info_axis)
      198    0.000    0.000    0.001    0.000 generic.py:4423(_protect_consolidate)
      198    0.000    0.000    0.001    0.000 generic.py:4433(_consolidate_inplace)
      198    0.000    0.000    0.001    0.000 generic.py:4436(f)
       99    0.000    0.000    0.192    0.002 generic.py:4563(values)
       99    0.001    0.000    0.019    0.000 generic.py:4765(dtypes)
       99    0.001    0.000    0.009    0.000 generic.py:4890(astype)
  1020096    0.331    0.000    0.509    0.000 generic.py:7(_check)
       99    0.000    0.000    0.010    0.000 generic.py:9675(logical_func)
       99    0.000    0.000    0.000    0.000 indexing.py:2321(convert_to_index_sliceable)
       99    0.000    0.000    0.003    0.000 indexing.py:2345(check_bool_indexer)
       99    0.002    0.000    0.004    0.000 indexing.py:2441(maybe_convert_indices)
      198    0.000    0.000    0.000    0.000 inference.py:119(is_iterator)
      891    0.001    0.000    0.005    0.000 inference.py:251(is_list_like)
       99    0.000    0.000    0.000    0.000 inference.py:364(is_dict_like)
   499356    0.156    0.000    0.266    0.000 inference.py:415(is_hashable)
       99    0.000    0.000    0.000    0.000 inspect.py:73(isclass)
      891    0.002    0.000    0.005    0.000 internals.py:116(__init__)
      297    0.001    0.000    0.034    0.000 internals.py:1237(take_nd)
      891    0.001    0.000    0.001    0.000 internals.py:127(_check_ndim)
       99    0.000    0.000    0.000    0.000 internals.py:184(is_categorical_astype)
      297    0.000    0.000    0.000    0.000 internals.py:199(external_values)
   998613    0.147    0.000    0.147    0.000 internals.py:203(internal_values)
      297    0.000    0.000    0.109    0.000 internals.py:213(get_values)
   998613    0.327    0.000    0.663    0.000 internals.py:222(to_dense)
      297    0.000    0.000    0.000    0.000 internals.py:229(fill_value)
      495    0.001    0.000    0.004    0.000 internals.py:2298(__init__)
     2178    0.001    0.000    0.001    0.000 internals.py:233(mgr_locs)
      891    0.001    0.000    0.001    0.000 internals.py:237(mgr_locs)
      396    0.000    0.000    0.003    0.000 internals.py:269(make_block_same_class)
      495    0.002    0.000    0.009    0.000 internals.py:3148(get_block_type)
      891    0.002    0.000    0.017    0.000 internals.py:3191(make_block)
       99    0.001    0.000    0.009    0.000 internals.py:3265(__init__)
       99    0.000    0.000    0.000    0.000 internals.py:3266(<listcomp>)
      594    0.001    0.000    0.003    0.000 internals.py:3307(shape)
     1782    0.001    0.000    0.002    0.000 internals.py:3309(<genexpr>)
      495    0.000    0.000    0.000    0.000 internals.py:3311(ndim)
   499257    0.527    0.000    1.341    0.000 internals.py:3315(set_axis)
       99    0.000    0.000    0.000    0.000 internals.py:3351(_is_single_block)
       99    0.002    0.000    0.005    0.000 internals.py:3363(_rebuild_blknos_and_blklocs)
      297    0.000    0.000    0.000    0.000 internals.py:3384(_get_items)
       99    0.000    0.000    0.005    0.000 internals.py:3404(get_dtypes)
       99    0.000    0.000    0.000    0.000 internals.py:3405(<listcomp>)
      198    0.000    0.000    0.000    0.000 internals.py:3473(__len__)
      297    0.000    0.000    0.000    0.000 internals.py:348(shape)
       99    0.001    0.000    0.002    0.000 internals.py:3488(_verify_integrity)
      396    0.000    0.000    0.000    0.000 internals.py:3490(<genexpr>)
       99    0.001    0.000    0.005    0.000 internals.py:3500(apply)
  1000098    0.218    0.000    0.218    0.000 internals.py:352(dtype)
      297    0.000    0.000    0.001    0.000 internals.py:356(ftype)
       99    0.000    0.000    0.000    0.000 internals.py:3561(<genexpr>)
       99    0.000    0.000    0.005    0.000 internals.py:3713(astype)
      495    0.000    0.000    0.000    0.000 internals.py:3776(is_consolidated)
       99    0.000    0.000    0.001    0.000 internals.py:3784(_consolidate_check)
       99    0.000    0.000    0.001    0.000 internals.py:3785(<listcomp>)
       99    0.000    0.000    0.000    0.000 internals.py:3789(is_mixed_type)
       99    0.000    0.000    0.191    0.002 internals.py:3922(as_array)
       99    0.056    0.001    0.190    0.002 internals.py:3953(_interleave)
      198    0.000    0.000    0.000    0.000 internals.py:4085(consolidate)
      297    0.000    0.000    0.000    0.000 internals.py:4101(_consolidate_inplace)
       99    0.001    0.000    0.044    0.000 internals.py:4388(reindex_indexer)
       99    0.000    0.000    0.034    0.000 internals.py:4423(<listcomp>)
       99    0.001    0.000    0.062    0.001 internals.py:4518(take)
      594    0.002    0.000    0.017    0.000 internals.py:4639(__init__)
  3495591    0.682    0.000    0.682    0.000 internals.py:4684(_block)
       99    0.000    0.000    0.000    0.000 internals.py:4709(index)
   998811    0.529    0.000    0.956    0.000 internals.py:4718(dtype)
      297    0.000    0.000    0.001    0.000 internals.py:4742(external_values)
   998613    0.566    0.000    0.914    0.000 internals.py:4745(internal_values)
   998613    0.782    0.000    1.901    0.000 internals.py:4752(get_values)
      198    0.000    0.000    0.000    0.000 internals.py:4774(_consolidate_inplace)
       99    0.000    0.000    0.007    0.000 internals.py:5044(_interleaved_dtype)
       99    0.000    0.000    0.000    0.000 internals.py:5048(<listcomp>)
       99    0.000    0.000    0.000    0.000 internals.py:5101(_extend_blocks)
       99    0.000    0.000    0.003    0.000 internals.py:573(astype)
       99    0.001    0.000    0.003    0.000 internals.py:577(_astype)
       99    0.000    0.000    0.001    0.000 internals.py:774(copy)
       99    0.000    0.000    0.004    0.000 missing.py:112(_isna_new)
       99    0.001    0.000    0.003    0.000 missing.py:189(_isna_ndarraylike)
       99    0.000    0.000    0.004    0.000 missing.py:32(isna)
       99    0.000    0.000    0.000    0.000 missing.py:376(array_equivalent)
       99    0.000    0.000    0.000    0.000 nanops.py:179(_get_fill_value)
       99    0.001    0.000    0.006    0.000 nanops.py:202(_get_values)
       99    0.000    0.000    0.000    0.000 nanops.py:256(_na_ok_dtype)
       99    0.000    0.000    0.000    0.000 nanops.py:260(_view_if_needed)
       99    0.000    0.000    0.007    0.000 nanops.py:318(nanany)
       99    0.000    0.000    0.000    0.000 numeric.py:110(is_all_dates)
      396    0.001    0.000    0.003    0.000 numeric.py:2491(seterr)
      396    0.001    0.000    0.001    0.000 numeric.py:2592(geterr)
      198    0.000    0.000    0.000    0.000 numeric.py:2887(__init__)
      198    0.000    0.000    0.002    0.000 numeric.py:2891(__enter__)
      198    0.000    0.000    0.001    0.000 numeric.py:2896(__exit__)
       99    0.000    0.000    0.002    0.000 numeric.py:35(__new__)
      693    0.000    0.000    0.003    0.000 numeric.py:433(asarray)
       99    0.000    0.000    0.001    0.000 numeric.py:504(asanyarray)
       99    0.000    0.000    0.008    0.000 numeric.py:64(_shallow_copy)
       99    0.000    0.000    0.000    0.000 numerictypes.py:1001(<listcomp>)
       99    0.000    0.000    0.000    0.000 numerictypes.py:1002(<listcomp>)
      198    0.002    0.000    0.003    0.000 numerictypes.py:927(_can_coerce_all)
     1881    0.001    0.000    0.001    0.000 numerictypes.py:936(<listcomp>)
       99    0.000    0.000    0.003    0.000 numerictypes.py:950(find_common_type)
       99    0.000    0.000    0.009    0.000 range.py:260(_shallow_copy)
      198    0.000    0.000    0.001    0.000 range.py:315(equals)
     1287    0.001    0.000    0.002    0.000 range.py:481(__len__)
      594    0.006    0.000    0.061    0.000 series.py:166(__init__)
       99    0.002    0.000    0.048    0.000 series.py:3069(apply)
       99    0.001    0.000    0.010    0.000 series.py:3203(_reduce)
      198    0.000    0.000    0.000    0.000 series.py:349(_constructor)
   499851    0.796    0.000    2.627    0.000 series.py:365(_set_axis)
   499851    0.255    0.000    0.255    0.000 series.py:391(_set_subtyp)
      792    0.001    0.000    0.002    0.000 series.py:401(name)
      495    0.003    0.000    0.022    0.000 series.py:4019(_sanitize_array)
      495    0.002    0.000    0.016    0.000 series.py:4036(_try_cast)
   500049    0.378    0.000    0.645    0.000 series.py:405(name)
   998811    0.448    0.000    1.404    0.000 series.py:412(dtype)
      297    0.000    0.000    0.001    0.000 series.py:432(values)
   998613    0.412    0.000    1.326    0.000 series.py:465(_values)
   998613    0.374    0.000    2.275    0.000 series.py:476(get_values)
      198    0.000    0.000    0.001    0.000 series.py:562(__len__)
       99    0.000    0.000    0.001    0.000 series.py:637(__array__)
   998514    1.469    0.000   15.215    0.000 series.py:764(__getitem__)
       99    0.000    0.000    0.000    0.000 {built-in method __new__ of type object at 0x9cff80}
      396    0.000    0.000    0.001    0.000 {built-in method builtins.all}
      198    0.000    0.000    0.001    0.000 {built-in method builtins.any}
   998613    0.096    0.000    0.096    0.000 {built-in method builtins.callable}
        1    0.000    0.000   26.802   26.802 {built-in method builtins.exec}
  4026825    1.271    0.000    2.597    0.000 {built-in method builtins.getattr}
     4950    0.002    0.000    0.002    0.000 {built-in method builtins.hasattr}
  1497969    0.245    0.000    0.246    0.000 {built-in method builtins.hash}
  4047912    0.987    0.000    1.499    0.000 {built-in method builtins.isinstance}
  1006434    0.136    0.000    0.136    0.000 {built-in method builtins.issubclass}
       99    0.000    0.000    0.000    0.000 {built-in method builtins.iter}
4009005/2009007    0.842    0.000    1.390    0.000 {built-in method builtins.len}
     1287    0.001    0.000    0.001    0.000 {built-in method builtins.max}
       99    0.000    0.000    0.000    0.000 {built-in method builtins.sum}
      297    0.001    0.000    0.001    0.000 {built-in method numpy.core.multiarray.arange}
1000098/999999    0.284    0.000    0.285    0.000 {built-in method numpy.core.multiarray.array}
      792    0.017    0.000    0.017    0.000 {built-in method numpy.core.multiarray.empty}
       99    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.putmask}
       99    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.zeros}
      792    0.000    0.000    0.000    0.000 {built-in method numpy.core.umath.geterrobj}
      396    0.000    0.000    0.000    0.000 {built-in method numpy.core.umath.seterrobj}
      396    0.000    0.000    0.000    0.000 {built-in method pandas._libs.algos.ensure_int64}
      100    0.000    0.000    0.000    0.000 {built-in method pandas._libs.algos.ensure_object}
       99    0.000    0.000    0.000    0.000 {built-in method pandas._libs.algos.ensure_platform_int}
       99    0.000    0.000    0.000    0.000 {built-in method pandas._libs.lib.infer_datetimelike_array}
        1    0.000    0.000    0.000    0.000 {built-in method pandas._libs.lib.is_datetime_array}
   998811    0.145    0.000    0.145    0.000 {built-in method pandas._libs.lib.is_float}
      297    0.000    0.000    0.000    0.000 {built-in method pandas._libs.lib.is_integer}
   998613    0.128    0.000    0.128    0.000 {built-in method pandas._libs.lib.is_scalar}